### PR TITLE
Add per test timeout

### PR DESCRIPTION
**Pull request by Momcilo42**
This allows for a test to timeout when hanging.
It's also more useful than the general timeout option as this shows if more than one test can timeout.

### CODE REVIEW

**Comment by Momcilo42** [comment]
@pbos Can you take a look?

**Comment by pbos** [comment]
Hi, sorry I'm out on parental leave until ~November. I'll take a look then.

@jleconte2 do you know off the top of your head how WebRTC deals with test timeouts? I wouldn't want us to duplicate functionality if we already offer something similar.

**Comment by jleconte2** [comment]
WebRTC runs gtest_parallel under LUCI infrastructure which provides its own timeouts management.
It currently does not use the timeouts provided by gtest_parallel.

**Comment by Momcilo42** [comment]
@pbos Can you take a look now?

**Comment by pbos** [comment]
It looks like upstream isn't interested in adding per-test-timeout (since gtest runners like blaze and cmake support timeout) and I think gtest-parallel falls within the scope of being a gtest runner. Thanks!

**Pull request merged**
